//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDF.Demo.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMemberLogon : SystemEntity
    {
        public string Password { get; set; }
        public string Secretkey { get; set; }
        public Nullable<int> LogOnCount { get; set; }
        public Nullable<bool> UserOnLine { get; set; }
        public string SessionKey { get; set; }
        public Nullable<System.DateTime> PreviousVisitTime { get; set; }
        public Nullable<System.DateTime> LastVisitTime { get; set; }
    
        public virtual SystemMember SystemMember { get; set; }
    }
}
