//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDF.Demo.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMember : SystemEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemMember()
        {
            this.SystemMemberRoles = new HashSet<SystemMemberRole>();
        }
    
        public string Account { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EnabledMark { get; set; }
        public bool IsSuperAdmin { get; set; }
        public string RealName { get; set; }
        public string QQ { get; set; }
    
        public virtual SystemMemberLogon SystemMemberLogon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMemberRole> SystemMemberRoles { get; set; }
    }
}
