#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Image/Upload.cshtml")]
    public partial class _Views_Image_Upload_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Image_Upload_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Image\Upload.cshtml"
  
   

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title></title>\r\n</head>\r\n<body>\r\n    <div>\r\n        <form");

WriteLiteral(" method=\"POST\"");

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n            <label>单文件:</label>\r\n            <input");

WriteLiteral(" name=\"FileModel\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" />\r\n            <br />\r\n            <label>多文件</label>\r\n            <input");

WriteLiteral(" name=\"FileModels\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" name=\"FileModels\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" />\r\n            <br />\r\n            <input");

WriteLiteral(" name=\"Name\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"file\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" />\r\n        </form>\r\n    </div>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
